arch: NestedUNet
batch_size: 2
dataset: mgm
deep_supervision: false
early_stopping: -1
epochs: 30
factor: 0.1
gamma: 0.6666666666666666
img_ext: .jpg
input_channels: 3
input_h: 416
input_w: 896
loss: BCEDiceLoss
lr: 0.001
mask_ext: .png
milestones: 1,2
min_lr: 0.001
momentum: 0.9
name: mgm_NestedUNet_woDS
nesterov: false
num_classes: 1
num_workers: 0
optimizer: SGD
patience: 2
scheduler: CosineAnnealingLR
weight_decay: 0.0001
